### ISSUE TITLE
Flatworld Chunks

### ISSUE THREAD

**Issue by LukeZurg22** [BentoBoxWorld/BSkyBlock#81]
**Description**
The bug involves two things, when spawning, the players spawn on flat chunks spawned in the distance, even with flat-world chunk clearing ON, no matter what I do it continues to generate more. Furthermore, it continues to generate them infinitely. I also have a spawn island of which has settings that reset, ownership from me is removed and redoing all of it is a pain.

**Steps to reproduce the behavior:**
1. Add add-on
2. Open server with plugin
3. Have a couple players make islands and eventually after testing you will see it.
4. Nonprofit

**Expected behavior**
You should expect to see flatworld chunks load in the voidworld.

**Screenshots**
Not necessary.

**Server Information:**

[Please complete the following information:]
 - OS: Linux
 - BentoBox version: 1.2.1
 - Addons installed? BSkyblock
 - Other plugins?
CoreProtect, LuckPerms, WorldEdit, PlaceholderAPI, PlugMan, RandomItems, Votifier, WorldGuard, ProtocolLib, DeathMessagesPrime, AdvancedHelp, Arconix, VotingPlugin, ImageMaps, HideAchievements, React, BroadcastXS, UltimateStacker, EnjinMinecraftPlugin, PluginLibrary, PremiumVanish, ServerlistMOTD, Vault, HeadDatabase, BentoBox, Parkour, CMIEInjector, Multiverse-Core, Shopkeepers, DiscordSRV, Multiverse-Inventories, QuickShop, CrateReloaded, CMI

**Additional context**
Not much, console when clear chunk is enabled spams that it is regenerating chunks in regions but seems to do nothing after a while.

**Comment by tastybento** [comment]
Clearly the generator isn't registering.

Share your console log after start up until the BENTOBOX logo (zip it up and drag and drop to this box).

Also type **bbox version** in console and share the output so we know what version of BSkyBlock you're using. 

You should see something like this in the log at the end:
```
[19:49:02 INFO]: Done (44.776s)! For help, type "help"
[19:49:02 INFO]: [BentoBox] Added world BSkyBlock (NORMAL)
[19:49:02 INFO]: [BentoBox] Hooking with Multiverse-Core...
[19:49:02 INFO]: Multiverse already knows about 'BSkyBlock_world'!
[19:49:02 INFO]: Success! Property generator was set to BentoBox
[19:49:02 INFO]: Multiverse already knows about 'BSkyBlock_world_nether'!
[19:49:02 INFO]: Success! Property generator was set to BentoBox
[19:49:02 INFO]: Multiverse already knows about 'BSkyBlock_world_the_end'!
[19:49:02 INFO]: Success! Property generator was set to BentoBox
[19:49:02 INFO]: 
  ____             _        ____
 |  _ \           | |      |  _ \             by tastybento and Poslovitch
 | |_) | ___ _ __ | |_ ___ | |_) | _____  __  2017 - 2019
 |  _ < / _ \ '_ \| __/ _ \|  _ < / _ \ \/ /
 | |_) |  __/ | | | || (_) | |_) | (_) >  <   v1.3.0-SNAPSHOT
 |____/ \___|_| |_|\__\___/|____/ \___/_/\_\  Loaded in 35669ms.

```

**Comment by tastybento** [comment]
For the spawn island resetting, that's something that's been fixed in later versions of BentoBox. 1.3.0. It's going to be released soon. If you like, try the latest builds from https://ci.codemc.org and see if they work for you.

**Comment by LukeZurg22** [comment]
02 23:00:51 [Server] INFO [Vault][Economy] CMI Economy hooked.
16.02 23:00:51 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
16.02 23:00:51 [Server] Startup Done (18.721s)! For help, type "help"
16.02 23:00:51 [Server] INFO [BentoBox] Added world Latest (NORMAL)
16.02 23:00:51 [Server] ERROR [BentoBox] Could not load objects from database! Error: null
16.02 23:00:51 [Server] INFO [BentoBox] Hooking with Multiverse-Core...
16.02 23:00:51 [Server] INFO Multiverse already knows about 'Latest'!
16.02 23:00:51 [Server] INFO Success! Property generator was set to BentoBox
16.02 23:00:51 [Server] INFO Multiverse already knows about 'Latest_nether'!
16.02 23:00:51 [Server] INFO Success! Property generator was set to BentoBox
16.02 23:00:51 [Server] INFO Multiverse already knows about 'Latest_the_end'!
16.02 23:00:51 [Server] INFO Success! Property generator was set to BentoBox
16.02 23:00:51 [Server] INFO ____             _        ____
16.02 23:00:51 [Server] INFO |  _ \           | |      |  _ \             by tastybento and Poslovitch
16.02 23:00:51 [Server] INFO | |_) | ___ _ __ | |_ ___ | |_) | _____  __  2017 - 2019
16.02 23:00:51 [Server] INFO |  _ < / _ \ '_ \| __/ _ \|  _ < / _ \ \/ /
16.02 23:00:51 [Server] INFO | |_) |  __/ | | | || (_) | |_) | (_) >  <   v1.2.1
16.02 23:00:51 [Server] INFO |____/ \___|_| |_|\__\___/|____/ \___/_/\_\  Loaded in 6073ms.
16.02 23:00:52 [Server] INFO [PlaceholderAPI] An update for PlaceholderAPI (v2.9.2) is available at:
16.02 23:00:52 [Server] INFO [PlaceholderAPI] https://www.spigotmc.org/resources/placeholderapi.6245/
16.02 23:00:52 [Server] INFO [BroadcastXS] The plugin is up to date.
16.02 23:00:52 [Server] INFO [QuickShop] New QuickShop released, now updated on SpigotMC.org!
16.02 23:00:52 [Server] INFO [QuickShop] Update here: https://www.spigotmc.org/resources/62575/
16.02 23:00:52 [Server] INFO [VotingPlugin] Successfully hooked into vault economy!
16.02 23:00:52 [Server] INFO [VotingPlugin] Hooked into vault permissions
16.02 23:00:52 [Server] INFO [CrateReloaded] Plugin is out of date. Running: 2.0.5, Latest: 2.0.7.
16.02 23:00:52 [Server] INFO [VotingPlugin] VotingPlugin has an update available! Your Version: 5.17.4 New Version: 5.18 Use /av download to get the latest update!
16.02 23:00:53 [Server] WARN [VotingPlugin] Detected an issue with voting sites, check the plugin startup log for more details
16.02 23:00:53 [Server] INFO [HeadDatabase] Succesfully loaded 20911 heads!
16.02 23:00:53 [Server] INFO [HeadDatabase] Succesfully loaded 13 featured tags!
16.02 23:00:53 [Server] INFO [PlaceholderAPI] 126 placeholder expansions are available on the cloud.

Also how do I check the latest builds from that link, cannot seem to find where to download the latest builds.

**Comment by tastybento** [comment]
BentoBox download link is: https://ci.codemc.org/job/BentoBoxWorld/job/BentoBox/
Pick a green build (the ones of the left), for example #818. However, watch out because these are development builds and not tested releases, so use at your own risk (actually all releases are use at your own risk!).
For BSkyBlock: https://ci.codemc.org/job/BentoBoxWorld/job/BSkyBlock/

See how that works out.

I also see an error in the database loading in the console log. Delete the old database, the whole worlds and everything when you try the new builds so that's it's a clean install.

**Comment by LukeZurg22** [comment]
Upon doing testing with a fresh install of the worlds, databases, configs and all. The world gen issue is still a problem.

**Comment by tastybento** [comment]
Understood. That's the super flat fixer trying to fix the chunks, but as the generator isn't working, it's not able to.

Please post you full console log from start up (the whole file please) and the result of doing /bbox version in the console.

**Comment by LukeZurg22** [comment]
https://pastebin.com/KUrUqczY

Here is the most recent log

**Comment by tastybento** [comment]
It looks like you only have one world on the server called Latest - is this correct?

Right now, Bentobox/Bskyblock does not support having the BSkyblock world as the main/sole world of the server. Maybe that’s the issue. 

Can you make another ticket for the spawn island thing?

**Comment by LukeZurg22** [comment]
There is no support? Our server is purely skyblock and needs spawn in the skyblock world... but ok.

**Comment by tastybento** [comment]
You can have players spawn in the Skyblock world and never “see” the default world but there does need to be a default world. It can never be used. The reason is because bskyblock loads not at startup but after the default world. That’s why it cannot be the generator. It’s a limitation of the architecture and not something that’s possible to fix as far as I know. 

I think we can look into putting a warning to help avoid this in the future and document it. 

Anyway it looks like that’s the issue so I’ll close this ticket now.
